CREATE TABLE IF NOT EXISTS vocabularies (
  id SERIAL PRIMARY KEY,
  korean VARCHAR(100) NOT NULL UNIQUE,
  romanization VARCHAR(150) NOT NULL,
  vietnamese_meaning VARCHAR(255) NOT NULL,
  category VARCHAR(100) NOT NULL,
  example_sentence TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO vocabularies (korean, romanization, vietnamese_meaning, category, example_sentence) VALUES
('안녕하세요', 'annyeonghaseyo', 'xin chào', 'chào hỏi', '안녕하세요, 만나서 반갑습니다.'),
('감사합니다', 'gamsahamnida', 'cảm ơn', 'chào hỏi', '도와줘서 감사합니다.'),
('죄송합니다', 'joesonghamnida', 'xin lỗi', 'chào hỏi', '늦어서 죄송합니다.'),
('안녕히 가세요', 'annyeonghi gaseyo', 'tạm biệt người đi', 'chào hỏi', '안녕히 가세요, 내일 봐요.'),
('안녕히 계세요', 'annyeonghi gyeseyo', 'tạm biệt người ở lại', 'chào hỏi', '안녕히 계세요, 저는 갑니다.'),
('네', 'ne', 'vâng', 'chào hỏi', '네, 알겠습니다.'),
('아니요', 'aniyo', 'không', 'chào hỏi', '아니요, 괜찮습니다.'),
('괜찮아요', 'gwaenchanayo', 'không sao', 'chào hỏi', '괜찮아요, 문제없어요.'),
('만나서 반갑습니다', 'mannaseo bangapseumnida', 'rất vui được gặp', 'chào hỏi', '만나서 반갑습니다.'),
('이름', 'ireum', 'tên', 'chào hỏi', '제 이름은 민수입니다.'),

('학교', 'hakgyo', 'trường học', 'trường học', '저는 학교에 갑니다.'),
('학생', 'haksaeng', 'học sinh', 'trường học', '학생이 책을 읽습니다.'),
('선생님', 'seonsaengnim', 'giáo viên', 'trường học', '선생님이 설명합니다.'),
('책', 'chaek', 'sách', 'trường học', '책을 펴세요.'),
('공책', 'gongchaek', 'vở', 'trường học', '공책에 쓰세요.'),
('연필', 'yeonpil', 'bút chì', 'trường học', '연필로 이름을 씁니다.'),
('수업', 'sueop', 'giờ học', 'trường học', '수업이 시작됩니다.'),
('교실', 'gyosil', 'lớp học', 'trường học', '교실이 조용합니다.'),
('숙제', 'sukje', 'bài tập về nhà', 'trường học', '숙제를 합니다.'),
('시험', 'siheom', 'kỳ thi', 'trường học', '내일 시험이 있습니다.'),

('밥', 'bap', 'cơm', 'đồ ăn', '저는 밥을 먹습니다.'),
('물', 'mul', 'nước', 'đồ ăn', '물을 마십니다.'),
('김치', 'gimchi', 'kimchi', 'đồ ăn', '김치가 맛있습니다.'),
('고기', 'gogi', 'thịt', 'đồ ăn', '고기를 좋아합니다.'),
('생선', 'saengseon', 'cá', 'đồ ăn', '생선을 먹습니다.'),
('과일', 'gwail', 'trái cây', 'đồ ăn', '과일을 삽니다.'),
('사과', 'sagwa', 'quả táo', 'đồ ăn', '사과가 빨갛습니다.'),
('우유', 'uyu', 'sữa', 'đồ ăn', '아침에 우유를 마십니다.'),
('커피', 'keopi', 'cà phê', 'đồ ăn', '커피 한 잔 주세요.'),
('빵', 'ppang', 'bánh mì', 'đồ ăn', '빵을 먹고 싶어요.'),

('가족', 'gajok', 'gia đình', 'gia đình', '우리 가족은 네 명입니다.'),
('아버지', 'abeoji', 'bố', 'gia đình', '아버지는 회사에 갑니다.'),
('어머니', 'eomeoni', 'mẹ', 'gia đình', '어머니는 요리합니다.'),
('형', 'hyeong', 'anh trai của nam', 'gia đình', '형은 키가 큽니다.'),
('오빠', 'oppa', 'anh trai của nữ', 'gia đình', '오빠는 학생입니다.'),
('누나', 'nuna', 'chị gái của nam', 'gia đình', '누나는 친절합니다.'),
('언니', 'eonni', 'chị gái của nữ', 'gia đình', '언니와 같이 갑니다.'),
('동생', 'dongsaeng', 'em', 'gia đình', '동생이 집에 있습니다.'),
('할머니', 'halmeoni', 'bà', 'gia đình', '할머니를 만납니다.'),
('할아버지', 'harabeoji', 'ông', 'gia đình', '할아버지는 웃습니다.'),

('오늘', 'oneul', 'hôm nay', 'thời gian', '오늘은 월요일입니다.'),
('내일', 'naeil', 'ngày mai', 'thời gian', '내일 만나요.'),
('어제', 'eoje', 'hôm qua', 'thời gian', '어제 공부했습니다.'),
('아침', 'achim', 'buổi sáng', 'thời gian', '아침에 운동합니다.'),
('점심', 'jeomsim', 'buổi trưa', 'thời gian', '점심을 먹습니다.'),
('저녁', 'jeonyeok', 'buổi tối', 'thời gian', '저녁에 집에 갑니다.'),
('지금', 'jigeum', 'bây giờ', 'thời gian', '지금 시간이 있어요.'),
('시간', 'sigan', 'thời gian', 'thời gian', '시간이 없습니다.'),
('분', 'bun', 'phút', 'thời gian', '십 분 기다립니다.'),
('주말', 'jumal', 'cuối tuần', 'thời gian', '주말에 쉽니다.')
ON CONFLICT (korean) DO NOTHING;
