apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: korean-vocab-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/jaydenhoang5291/korean_basic_vocab_app
    targetRevision: main
    path: apps/korean-vocab-app
  destination:
    server: https://kubernetes.default.svc
    namespace: korean-vocab
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true